[package]
name = "udp-bcast-relay-rs"
version = "0.2.0"
edition = "2024"
license = "GPL-3.0-or-later"
rust-version = "1.93"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["cargo"] }
libc = "0.2.174"
log = "0.4.22"
netdev = "0.42"
socket2 = { version = "0.6.0", features = ["all"] }
stderrlog = { version = "0.6.0", default-features = false }

[dev-dependencies]
assert_cmd = "2.1.2"
testcontainers = "0.27"
tokio = { version = "1", features = ["full"] }
